class Errors:
    LOST_CONNECTION = 0
    NOT_AUTHENTICATED = 1
    INVALID_AUTHENTICATION_TOKEN = 2
    INVALID_REQUEST_DATA = 3
    USER_BY_EMAIL_NOT_FOUND = 4
    INVALID_PASSWORD = 5
    EMAIL_ALREADY_IN_USE = 6
    ALREADY_LOGGED_IN = 7
    CHAT_WAS_NOT_FOUND = 8
    INVALID_CHAT_OWNER = 9
    NOT_ENOUGH_PARTICIPANTS = 10
